import Seo from "@/components/Seo";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const TemplatesExport = () => {
  return (
    <div>
      <Seo title="Templates & Export — Scollab" description="Assemble approved answers and export polished PDFs." />
      <h1 className="text-2xl font-bold mb-4">Templates & Export Composer</h1>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Card className="lg:col-span-1">
          <CardHeader><CardTitle>Template picker</CardTitle></CardHeader>
          <CardContent className="space-y-3">
            {[
              { id: "compact", name: "Exam-compact" },
              { id: "detailed", name: "Study-detailed" },
              { id: "pocket", name: "Pocket-summary" },
            ].map((t) => (
              <label key={t.id} className="flex items-center gap-3 rounded-md border p-3 cursor-pointer hover:bg-accent/50">
                <input type="radio" name="template" className="accent-current" />
                <span className="text-sm">{t.name}</span>
              </label>
            ))}
          </CardContent>
        </Card>

        <Card className="lg:col-span-1">
          <CardHeader><CardTitle>Cover & Footer</CardTitle></CardHeader>
          <CardContent className="space-y-3">
            <div>
              <Label>Title</Label>
              <Input placeholder="Course pack title" />
            </div>
            <div>
              <Label>Footer</Label>
              <Input placeholder="Generated by Scollab • College name" />
            </div>
            <Button className="elevated">Preview</Button>
          </CardContent>
        </Card>

        <Card className="lg:col-span-1">
          <CardHeader><CardTitle>Preview</CardTitle></CardHeader>
          <CardContent>
            <div className="aspect-[3/4] w-full rounded-md border bg-card/50 grid place-items-center text-sm text-muted-foreground">PDF preview</div>
            <div className="mt-3 flex gap-2">
              <Button>Download PDF</Button>
              <Button variant="secondary">Publish to groups</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default TemplatesExport;
